image: Visual Studio 2019
#build_script:
  #project: AuditFondLab1.sln
 # - dotnet test #AuditFondLab1.sln


before_build:
  - nuget restore
  
  
test:
  assemblies:
    - '**\*.AuditFondLab1.dll'

$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOutput.xml))
