version: '1.0.{build}'
#assembly_info:
#  patch: true
#  file: '**\*.csproj'
dotnet_csproj:
  patch: true
  file: 'AuditFondLab1.csproj'
  version: 5.0.3
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
  #project: AuditFondLab1.sln
  - dotnet test
before_build:
  - nuget restore
